

# This file was *autogenerated* from the file sage/attacks/algebraic_degree_growth.sage
from sage.all_cmdline import *   # import sage library

_sage_const_97 = Integer(97); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)# SageMath: degree growth experiment on small state
# Uses t=2 to keep memory usage manageable in CI.
p = _sage_const_97 
F = GF(p)
alpha = _sage_const_5 
t = _sage_const_2   # state width (small to avoid memory explosion)

R = PolynomialRing(F, ['x%d' % i for i in range(t)])
xs = R.gens()

def sbox_full(state):
    return [x**alpha for x in state]

def sbox_partial(state):
    return [state[_sage_const_0 ]**alpha] + list(state[_sage_const_1 :])

# Simple MDS: 2x2 matrix [[2,1],[1,2]]
def mds(state):
    return [
        _sage_const_2 *state[_sage_const_0 ] + state[_sage_const_1 ],
        state[_sage_const_0 ] + _sage_const_2 *state[_sage_const_1 ],
    ]

def add_constants(state, r):
    return [s + F(r * t + i + _sage_const_1 ) for i, s in enumerate(state)]

# Track degree through rounds
state = list(xs)
print("Round | Degree | Expected (alpha^r)")
print("------+--------+-------------------")
for r in range(_sage_const_4 ):
    # Full round
    state = sbox_full(state)
    state = mds(state)
    state = add_constants(state, r)
    max_deg = max(s.degree() for s in state)
    expected = alpha**(r + _sage_const_1 )
    print(f"  {r+_sage_const_1 :3d} | {max_deg:>6} | {expected}")

