

# This file was *autogenerated* from the file sage/attacks/differential_uniformity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)# SageMath: differential uniformity of x^alpha
p = _sage_const_101 
F = GF(p)
alpha = _sage_const_5 

# Compute full DDT for small field
max_prob = _sage_const_0 
for delta_in in range(_sage_const_1 , p):
    counts = {}
    for x in range(p):
        delta_out = F(F(x + delta_in)**alpha - F(x)**alpha)
        delta_out = int(delta_out)
        counts[delta_out] = counts.get(delta_out, _sage_const_0 ) + _sage_const_1 
    local_max = max(counts.values())
    if local_max > max_prob:
        max_prob = local_max

print(f"Differential uniformity of x^{alpha} over F_{p}: {max_prob}")
print(f"Max differential probability: {max_prob}/{p} = {float(max_prob/p):.6f}")

