

# This file was *autogenerated* from the file sage/attacks/groebner_solving_degree.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)# Estimate solving degree via the Hilbert regularity index
p = _sage_const_101 
F = GF(p)
R = PolynomialRing(F, order='degrevlex', names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)

# System of 3 quadratic equations in 3 variables
f1 = x**_sage_const_2  + _sage_const_2 *y*z + _sage_const_3 
f2 = y**_sage_const_2  + x*z + _sage_const_7 
f3 = z**_sage_const_2  + x*y + _sage_const_11 

I = R.ideal([f1, f2, f3])

# Compute Groebner basis first
G = I.groebner_basis()
print(f"Groebner basis has {len(G)} elements")
print(f"Max degree in GB: {max(g.degree() for g in G)}")

# Predicted Hilbert series under regularity assumption
# For m equations of degree d in n variables:
# HS(z) = (1-z^d)^m / (1-z)^n
# For 3 equations of degree 2 in 3 variables:
# HS(z) = (1-z^2)^3 / (1-z)^3 = (1+z)^3 = 1 + 3z + 3z^2 + z^3
S = PowerSeriesRing(QQ, default_prec=_sage_const_10 , names=('z',)); (z,) = S._first_ngens(1)
HS_predicted = prod(_sage_const_1  - z**_sage_const_2  for _ in range(_sage_const_3 )) / (_sage_const_1  - z)**_sage_const_3 
print(f"\nPredicted HS (regular assumption):")
print(f"  {HS_predicted}")
print(f"  First non-positive coeff at degree: ", end="")
coeffs = HS_predicted.list()
found = False
for d, c in enumerate(coeffs):
    if c <= _sage_const_0 :
        print(f"{d} (solving degree)")
        found = True
        break
if not found:
    # For zero-dimensional ideals, the solving degree is
    # the index of the first zero coefficient
    print(f"{len(coeffs)} (all coefficients positive up to degree {len(coeffs)-_sage_const_1 })")

