

# This file was *autogenerated* from the file sage/attacks/groebner_practical_complexity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_42 = Integer(42); _sage_const_17 = Integer(17); _sage_const_89 = Integer(89)# SageMath: Groebner basis on a toy system
# (illustrative - real attacks use much larger fields)
p = _sage_const_101 
F = GF(p)
R = PolynomialRing(F, 'x,y,z', order='degrevlex')
x, y, z = R.gens()

# Toy 1-round system: S-box x^5, simple linear layer
alpha = _sage_const_5 
# Round: apply S-box then add constants
f1 = x**alpha + _sage_const_2 *y**alpha + _sage_const_3 *z**alpha - _sage_const_42 
f2 = _sage_const_3 *x**alpha + y**alpha + _sage_const_2 *z**alpha - _sage_const_17 
f3 = _sage_const_2 *x**alpha + _sage_const_3 *y**alpha + z**alpha - _sage_const_89 

I = R.ideal([f1, f2, f3])
print("Computing Groebner basis...")
G = I.groebner_basis()
print(f"Groebner basis has {len(G)} elements")
for g in G:
    print(f"  degree {g.degree()}: {g}")

