

# This file was *autogenerated* from the file sage/attacks/groebner_toy_system.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1)# Build and visualize a Macaulay matrix
p = _sage_const_101 
F = GF(p)
R = PolynomialRing(F, order='degrevlex', names=('x', 'y',)); (x, y,) = R._first_ngens(2)

# Two quadratic polynomials
f1 = x**_sage_const_2  + _sage_const_3 *x*y + _sage_const_2 *y**_sage_const_2  - _sage_const_1 
f2 = _sage_const_2 *x**_sage_const_2  + x*y + y**_sage_const_2  - _sage_const_3 

print(f"f1 = {f1}")
print(f"f2 = {f2}")

# Build Macaulay matrix at degree D=2 (no extension needed)
# At degree 2, we just use f1 and f2 directly
D = _sage_const_2 
# All monomials up to degree D
mons = [x**_sage_const_2 , x*y, y**_sage_const_2 , x, y, R(_sage_const_1 )]
print(f"\nDegree-{D} Macaulay matrix")
print(f"Monomials: {mons}")

rows_polys = [f1, f2]
M2 = matrix(F, len(rows_polys), len(mons))
for i, poly in enumerate(rows_polys):
    for j, mon in enumerate(mons):
        M2[i, j] = poly.monomial_coefficient(mon)
print(f"\nM_2 ({M2.nrows()} x {M2.ncols()}):")
print(M2)

# Now extend to degree D=3: multiply each f_i by {1, x, y}
D = _sage_const_3 
mons3 = [x**_sage_const_3 , x**_sage_const_2 *y, x*y**_sage_const_2 , y**_sage_const_3 , x**_sage_const_2 , x*y, y**_sage_const_2 , x, y, R(_sage_const_1 )]
multipliers = [R(_sage_const_1 ), x, y]

rows_polys3 = []
row_labels = []
for f, name in [(f1, 'f1'), (f2, 'f2')]:
    for m in multipliers:
        rows_polys3.append(m * f)
        row_labels.append(f"{m}*{name}")

M3 = matrix(F, len(rows_polys3), len(mons3))
for i, poly in enumerate(rows_polys3):
    for j, mon in enumerate(mons3):
        M3[i, j] = poly.monomial_coefficient(mon)

print(f"\nDegree-{D} Macaulay matrix")
print(f"Monomials: {mons3}")
print(f"Row labels: {row_labels}")
print(f"\nM_3 ({M3.nrows()} x {M3.ncols()}):")
print(M3)
print(f"Rank: {M3.rank()}")
print(f"\nRow echelon form:")
print(M3.echelon_form())

