

# This file was *autogenerated* from the file sage/attacks/groebner_degree_falls.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1)# S-polynomial computation
p = _sage_const_101 
F = GF(p)
R = PolynomialRing(F, order='degrevlex', names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)

f = _sage_const_2 *x**_sage_const_3 *y + _sage_const_3 *x*y**_sage_const_2  + _sage_const_5 
g = x**_sage_const_2 *y**_sage_const_2  + _sage_const_4 *y**_sage_const_3  + _sage_const_1 

print(f"f = {f}")
print(f"g = {g}")
print(f"LM(f) = {f.lm()}")
print(f"LM(g) = {g.lm()}")

# Compute S-polynomial manually
L = lcm(f.lm(), g.lm())
print(f"lcm(LM(f), LM(g)) = {L}")

S_fg = (L // f.lt()) * f - (L // g.lt()) * g
print(f"\nS(f, g) = {S_fg}")
print(f"Degree of S(f,g): {S_fg.degree()}")
print(f"(Leading terms cancelled: degree dropped from {L.degree()})")

# Verify with Sage's built-in
# Compute Groebner basis of {f, g} to see S-polynomial reduction in action
I = R.ideal([f, g])
G = I.groebner_basis()
print(f"\nGroebner basis of <f, g>:")
for i, gi in enumerate(G):
    print(f"  g{i+_sage_const_1 }: {gi}")

