

# This file was *autogenerated* from the file sage/attacks/groebner_semi_regularity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_42 = Integer(42); _sage_const_17 = Integer(17); _sage_const_89 = Integer(89); _sage_const_1 = Integer(1)# 1-round AO system over a small field
p = _sage_const_101 
F = GF(p)
R = PolynomialRing(F, order='degrevlex', names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)
alpha = _sage_const_5 

# One round: S-box then linear mix then constants
# Output = M * S-box(input) + constants
# We set up equations: output is known, solve for input
f1 = x**alpha + _sage_const_2 *y**alpha + _sage_const_3 *z**alpha - _sage_const_42 
f2 = _sage_const_3 *x**alpha + y**alpha + _sage_const_2 *z**alpha - _sage_const_17 
f3 = _sage_const_2 *x**alpha + _sage_const_3 *y**alpha + z**alpha - _sage_const_89 

I = R.ideal([f1, f2, f3])
G = I.groebner_basis()

print(f"System: 3 equations of degree {alpha} in 3 variables over F_{p}")
print(f"Groebner basis has {len(G)} elements:\n")
for i, g in enumerate(G):
    print(f"  g{i+_sage_const_1 } (degree {g.degree()}): {g}")

# The last element is univariate in z -> we can read off solutions
print(f"\nVariety (solutions):")
V = I.variety()
for sol in V:
    print(f"  x={sol[x]}, y={sol[y]}, z={sol[z]}")

