

# This file was *autogenerated* from the file sage/attacks/interpolation_degree.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_56 = Integer(56); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2)# SageMath: degree growth simulation
alpha = _sage_const_5 
full_rounds = _sage_const_8 
partial_rounds = _sage_const_56 
t = _sage_const_3   # state width

# Full rounds: degree grows as alpha^r across all elements
# Partial rounds: degree grows as alpha^r for one element
degree_full = alpha**(full_rounds // _sage_const_2 )
degree_partial = alpha**partial_rounds
degree_after_second_full = degree_full * alpha**(full_rounds // _sage_const_2 )

total_degree = degree_full * degree_partial * degree_full
print(f"Upper bound on degree after all rounds: {total_degree}")
print(f"log2(degree): {float(log(total_degree, _sage_const_2 )):.1f}")
print(f"log2(p) for BN254: ~254")

