

# This file was *autogenerated* from the file sage/poseidon/permutation.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_97 = Integer(97); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_14 = Integer(14)# Poseidon permutation reference implementation
# See: https://eprint.iacr.org/2019/458
#
# This is a minimal reference implementation for educational purposes.
# It implements the core Poseidon permutation over a prime field.

def poseidon_permutation(state, MDS, round_constants, alpha, R_F, R_P):
    """
    Poseidon permutation.

    Parameters:
        state: list of field elements (length t)
        MDS: t x t MDS matrix over the field
        round_constants: list of t-element lists, one per round
        alpha: S-box exponent
        R_F: number of full rounds
        R_P: number of partial rounds
    """
    t = len(state)
    F = state[_sage_const_0 ].parent()
    round_idx = _sage_const_0 

    # First half of full rounds
    for r in range(R_F // _sage_const_2 ):
        # AddRoundConstants
        state = [state[i] + round_constants[round_idx][i] for i in range(t)]
        # S-box (full)
        state = [x**alpha for x in state]
        # MDS
        state = list(MDS * vector(state))
        round_idx += _sage_const_1 

    # Partial rounds
    for r in range(R_P):
        # AddRoundConstants
        state = [state[i] + round_constants[round_idx][i] for i in range(t)]
        # S-box (partial: only first element)
        state[_sage_const_0 ] = state[_sage_const_0 ]**alpha
        # MDS
        state = list(MDS * vector(state))
        round_idx += _sage_const_1 

    # Second half of full rounds
    for r in range(R_F // _sage_const_2 ):
        # AddRoundConstants
        state = [state[i] + round_constants[round_idx][i] for i in range(t)]
        # S-box (full)
        state = [x**alpha for x in state]
        # MDS
        state = list(MDS * vector(state))
        round_idx += _sage_const_1 

    return state


# --- Example usage with a small field ---
if __name__ == "__main__":
    p = _sage_const_97   # small prime for demonstration (gcd(5, 96) = 1)
    F = GF(p)
    t = _sage_const_3 
    alpha = _sage_const_5 
    R_F = _sage_const_8 
    R_P = _sage_const_14 

    assert gcd(alpha, p - _sage_const_1 ) == _sage_const_1 , "alpha must be coprime to p-1"

    # Simple Cauchy MDS matrix
    xs = [F(i) for i in range(t)]
    ys = [F(i + t) for i in range(t)]
    MDS = matrix(F, t, t, lambda i, j: _sage_const_1  / (xs[i] - ys[j]))

    # Generate round constants (deterministic, not cryptographically secure)
    total_rounds = R_F + R_P
    round_constants = []
    for r in range(total_rounds):
        rc = [F(r * t + i + _sage_const_1 ) for i in range(t)]
        round_constants.append(rc)

    # Test permutation
    input_state = [F(_sage_const_1 ), F(_sage_const_2 ), F(_sage_const_3 )]
    output_state = poseidon_permutation(
        input_state, MDS, round_constants, alpha, R_F, R_P
    )
    print(f"Input:  {input_state}")
    print(f"Output: {output_state}")

