

# This file was *autogenerated* from the file sage/anemoi/flystel.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_97 = Integer(97); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_42 = Integer(42); _sage_const_17 = Integer(17)# Anemoi Flystel construction reference implementation
# See: https://eprint.iacr.org/2022/840
#
# Implements the open Flystel S-box used in Anemoi.

def open_flystel(x, y, alpha, beta, gamma, delta, F):
    """
    Open Flystel construction.

    Parameters:
        x, y: input pair in F
        alpha: S-box exponent (must satisfy gcd(alpha, p-1) = 1)
        beta, gamma, delta: Flystel parameters in F
        F: the finite field
    """
    alpha_inv = inverse_mod(int(alpha), int(F.characteristic()) - _sage_const_1 )

    # Quadratic function
    def Q(t):
        return t**_sage_const_2  + beta * t

    # Forward evaluation
    v = x - Q(y)
    e = F(v)**alpha_inv  # "expensive" direction
    u = y - e

    # Output
    x_out = v + gamma
    y_out = u + delta

    return x_out, y_out


# --- Example usage ---
if __name__ == "__main__":
    p = _sage_const_97 
    F = GF(p)
    alpha = _sage_const_5 

    assert gcd(alpha, p - _sage_const_1 ) == _sage_const_1 

    # Flystel parameters
    beta = F(_sage_const_3 )
    gamma = F(_sage_const_7 )
    delta = F(_sage_const_11 )

    # Test
    x, y = F(_sage_const_42 ), F(_sage_const_17 )
    x_out, y_out = open_flystel(x, y, alpha, beta, gamma, delta, F)
    print(f"Input:  ({x}, {y})")
    print(f"Output: ({x_out}, {y_out})")

