

# This file was *autogenerated* from the file sage/arithmetization/air_inverse_sbox.sage
from sage.all_cmdline import *   # import sage library

_sage_const_97 = Integer(97); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_42 = Integer(42); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_14 = Integer(14); _sage_const_8 = Integer(8); _sage_const_57 = Integer(57)# SageMath: demonstrate the inverse S-box advantage in AIR
# Both directions use the same constraint degree

p = _sage_const_97 
F = GF(p)
alpha = _sage_const_5 
alpha_inv = inverse_mod(alpha, p - _sage_const_1 )

x = F(_sage_const_42 )

# Forward S-box: y = x^alpha
y = x**alpha
# AIR transition constraint: y - x^alpha == 0 (degree alpha)
assert y - x**alpha == _sage_const_0 
print(f"Forward S-box: y = x^{alpha}")
print(f"  x = {x}, y = {y}")
print(f"  Constraint: y - x^{alpha} = 0  (degree {alpha})")

print()

# Inverse S-box: z = x^(1/alpha) = x^alpha_inv
z = x**alpha_inv
# AIR transition constraint: x - z^alpha == 0 (degree alpha!)
assert x - z**alpha == _sage_const_0 
print(f"Inverse S-box: z = x^(1/{alpha})")
print(f"  x = {x}, z = {z}")
print(f"  Constraint: x - z^{alpha} = 0  (still degree {alpha}!)")

print()
print("Both directions use degree-{} constraints.".format(alpha))
print("Rescue gets 2x nonlinearity for the same AIR cost per round.")

# Compare total constraints: Rescue vs Poseidon
print()
print("Comparison for t=3:")
print(f"  Poseidon full round: {_sage_const_3 } constraints of degree {alpha}")
print(f"  Rescue full round: {_sage_const_3 }+{_sage_const_3 } = {_sage_const_6 } constraints of degree {alpha}")
print(f"  But Rescue needs ~14 rounds vs Poseidon's ~65")
print(f"  Rescue AIR total: ~{_sage_const_14  * _sage_const_6 } constraints")
print(f"  Poseidon AIR total: ~{_sage_const_8  * _sage_const_3  + _sage_const_57  * _sage_const_1 } constraints (full+partial)")

