

# This file was *autogenerated* from the file sage/arithmetization/air_trace.sage
from sage.all_cmdline import *   # import sage library

_sage_const_97 = Integer(97); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_22 = Integer(22); _sage_const_33 = Integer(33); _sage_const_2 = Integer(2); _sage_const_50 = Integer(50)# SageMath: AIR trace simulation for a Poseidon-like round
# Demonstrates how the execution trace looks for one full round

p = _sage_const_97   # small prime for clarity (gcd(5, 96) = 1)
F = GF(p)
alpha = _sage_const_5 
t = _sage_const_3   # state width

# MDS matrix (Cauchy construction)
xs = [F(i) for i in range(t)]
ys = [F(i + t) for i in range(t)]
M = matrix(F, t, t, lambda i, j: _sage_const_1  / (xs[i] - ys[j]))

# Round constants (arbitrary for demonstration)
rc = [F(_sage_const_11 ), F(_sage_const_22 ), F(_sage_const_33 )]

def poseidon_full_round(state, rc, M, alpha):
    """One full round: AddRC -> S-box -> MDS"""
    # AddRoundConstants
    state = [state[i] + rc[i] for i in range(len(state))]
    # S-box on all elements
    state = [x**alpha for x in state]
    # MDS
    v = vector(F, state)
    v = M * v
    return list(v)

# Initial state
state = [F(_sage_const_1 ), F(_sage_const_2 ), F(_sage_const_3 )]
print("AIR trace for one Poseidon full round (t=3, alpha=5)")
print("=" * _sage_const_50 )
print(f"Row 0 (input):  {state}")

new_state = poseidon_full_round(state, rc, M, alpha)
print(f"Row 1 (output): {new_state}")

print()
print("Transition constraints (degree 5):")
# After adding round constants
state_rc = [state[i] + rc[i] for i in range(t)]
for j in range(t):
    sbox_out = state_rc[j]**alpha
    print(f"  col_{j}: verify S-box output = (input + rc)^{alpha}")

print()
print(f"Number of transition constraints: {t} (one per column)")
print(f"Constraint degree: {alpha}")
print(f"MDS is absorbed into the linear combination (free)")

