

# This file was *autogenerated* from the file sage/arithmetization/plonkish_gates.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_45 = Integer(45); _sage_const_1 = Integer(1); _sage_const_99 = Integer(99); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_57 = Integer(57)# SageMath: PlonK-ish gate simulation
# Demonstrate how a degree-5 custom gate encodes x^5 in one row

p = _sage_const_101 
F = GF(p)

# A PlonK-ish row has advice columns (witness) and selector columns (fixed).
# Custom gate: s_sbox * (w0^5 - w1) = 0

def verify_sbox_gate(w0, w1, selector):
    """Check the custom gate constraint."""
    return selector * (w0**_sage_const_5  - w1) == _sage_const_0 

# Active row (selector = 1): S-box gate
x = F(_sage_const_7 )
y = x**_sage_const_5 
print("PlonK-ish S-box gate (degree 5)")
print("=" * _sage_const_45 )
print(f"Gate equation: s_sbox * (w0^5 - w1) = 0")
print(f"  w0 = {x}, w1 = {y}, selector = 1")
print(f"  Constraint satisfied? {verify_sbox_gate(x, y, F(_sage_const_1 ))}")
print(f"  Cost: 1 row (vs 3 R1CS constraints)")

print()

# Inactive row (selector = 0): gate does not apply
print(f"Inactive row: selector = 0")
print(f"  w0 = {F(_sage_const_99 )}, w1 = {F(_sage_const_0 )}, selector = 0")
print(f"  Constraint satisfied? {verify_sbox_gate(F(_sage_const_99 ), F(_sage_const_0 ), F(_sage_const_0 ))}")

print()
print("Full Poseidon round in PlonK-ish (t=3, alpha=5):")
print("  Option A: 3 rows with degree-5 S-box gate each")
print("  Option B: 1 wide row combining S-box + MDS")
print()

# Simulate option A: separate rows
state = [F(_sage_const_1 ), F(_sage_const_2 ), F(_sage_const_3 )]
print("Option A trace (3 rows per full round):")
for i, x in enumerate(state):
    y = x**_sage_const_5 
    print(f"  Row {i}: w0={x}, w1={y}")
    assert verify_sbox_gate(x, y, F(_sage_const_1 ))

# Compare cost across full permutation
t = _sage_const_3 
R_F = _sage_const_8 
R_P = _sage_const_57 
option_a_rows = R_F * t + R_P * _sage_const_1   # full rounds: t rows, partial: 1 row
print(f"\\nTotal rows (option A): {R_F}*{t} + {R_P}*1 = {option_a_rows}")
print(f"Compare to R1CS: {R_F * t * _sage_const_3  + R_P * _sage_const_1  * _sage_const_3 } constraints")

