

# This file was *autogenerated* from the file sage/arithmetization/r1cs_constraint_count.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_55 = Integer(55); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_8 = Integer(8); _sage_const_57 = Integer(57)# SageMath: R1CS constraint count for x^alpha via square-and-multiply
# Each intermediate multiplication costs exactly one R1CS constraint.

def sbox_r1cs_chain(alpha):
    """
    Return the multiplication chain for x^alpha and count R1CS constraints.
    Uses binary method (square-and-multiply).
    """
    if alpha <= _sage_const_1 :
        return [], _sage_const_0 
    bits = ZZ(alpha).digits(_sage_const_2 )  # LSB first
    steps = []
    # Start: we have x (cost 0)
    # Squarings give x^2, x^4, x^8, ...
    # We multiply in the bits that are set
    acc_exp = _sage_const_1 
    constraints = _sage_const_0 
    powers = {_sage_const_1 : 'x'}
    current_sq = _sage_const_1 

    # Build addition chain from binary representation
    chain = []
    for i in range(len(bits) - _sage_const_1 ):
        # Square
        new_exp = current_sq * _sage_const_2 
        chain.append(f"x^{new_exp} = x^{current_sq} * x^{current_sq}")
        constraints += _sage_const_1 
        current_sq = new_exp

    # Now multiply together the powers where bits are set
    result_exp = _sage_const_0 
    parts = []
    for i, b in enumerate(bits):
        if b == _sage_const_1 :
            parts.append(_sage_const_2 **i)

    # Combine parts
    if len(parts) >= _sage_const_2 :
        acc = parts[_sage_const_0 ]
        for p in parts[_sage_const_1 :]:
            chain.append(f"x^{acc + p} = x^{acc} * x^{p}")
            constraints += _sage_const_1 
            acc = acc + p

    return chain, constraints

print("R1CS constraint chains for common S-box exponents")
print("=" * _sage_const_55 )
for alpha in [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 ]:
    chain, cost = sbox_r1cs_chain(alpha)
    print(f"\\nalpha = {alpha}: {cost} constraints")
    for step in chain:
        print(f"  {step}")

print("\\n" + "=" * _sage_const_55 )
print("\\nFull Poseidon permutation R1CS cost (t=3, alpha=5)")
t = _sage_const_3 
R_F = _sage_const_8 
R_P = _sage_const_57 
_, sbox_cost = sbox_r1cs_chain(_sage_const_5 )
full_round_constraints = t * sbox_cost  # all elements get S-box
partial_round_constraints = _sage_const_1  * sbox_cost  # only first element
total = R_F * full_round_constraints + R_P * partial_round_constraints
print(f"  S-box cost per element: {sbox_cost} constraints")
print(f"  Full round ({t} S-boxes): {full_round_constraints} constraints")
print(f"  Partial round (1 S-box): {partial_round_constraints} constraints")
print(f"  Total: {R_F}*{full_round_constraints} + {R_P}*{partial_round_constraints} = {total} constraints")
print(f"  (MDS matrix is free in R1CS: linear operations cost 0)")

