

# This file was *autogenerated* from the file sage/foundations/field_arithmetic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_42 = Integer(42); _sage_const_17 = Integer(17); _sage_const_1 = Integer(1)# SageMath: basic field arithmetic
p = _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 
F = GF(p)
a = F(_sage_const_42 )
b = F(_sage_const_17 )
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"a^(-1) = {a**(-_sage_const_1 )}")

