

# This file was *autogenerated* from the file sage/foundations/mds_matrix.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_123456789 = Integer(123456789)# SageMath: power map S-box
p = _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 
F = GF(p)
alpha = _sage_const_5 
# Verify gcd condition
assert gcd(alpha, p - _sage_const_1 ) == _sage_const_1 
# Compute inverse exponent
alpha_inv = inverse_mod(alpha, p - _sage_const_1 )
print(f"alpha = {alpha}")
print(f"alpha_inv = {alpha_inv}")
# Verify S-box is a permutation
x = F(_sage_const_123456789 )
assert F(x**alpha)**alpha_inv == x
print("S-box round-trip verified: S_inv(S(x)) == x")

