

# This file was *autogenerated* from the file sage/foundations/power_map_sbox.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_31 = Integer(31); _sage_const_1 = Integer(1); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_64 = Integer(64); _sage_const_32 = Integer(32); _sage_const_72 = Integer(72); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5)# SageMath: 2-adicity and S-box exponent for each STARK-friendly field
fields = [
    ("Mersenne-31", _sage_const_2 **_sage_const_31  - _sage_const_1 ),
    ("BabyBear",    _sage_const_2 **_sage_const_31  - _sage_const_2 **_sage_const_27  + _sage_const_1 ),
    ("KoalaBear",   _sage_const_2 **_sage_const_31  - _sage_const_2 **_sage_const_24  + _sage_const_1 ),
    ("Goldilocks",  _sage_const_2 **_sage_const_64  - _sage_const_2 **_sage_const_32  + _sage_const_1 ),
]

print("STARK-friendly fields: 2-adicity and smallest valid S-box exponent")
print("=" * _sage_const_72 )
print(f"{'Field':>12} | {'p':>22} | {'bits':>4} | {'_sage_const_2 -adic':>6} | {'min alpha':>9}")
print("-" * _sage_const_72 )
for name, p in fields:
    assert is_prime(p), f"{name} is not prime!"
    bits = ZZ(p).nbits()
    # 2-adicity: largest k such that 2^k divides p-1
    two_adicity = valuation(p - _sage_const_1 , _sage_const_2 )
    # Smallest alpha >= 3 with gcd(alpha, p-1) = 1
    alpha = _sage_const_3 
    while gcd(alpha, p - _sage_const_1 ) != _sage_const_1 :
        alpha += _sage_const_2   # only odd candidates
    print(f"{name:>12} | {p:>22} | {bits:>4} | {two_adicity:>6} | {alpha:>9}")

print()
# Verify extension field irreducible polynomials
print("Extension field verification:")
R = GF(_sage_const_2 **_sage_const_31  - _sage_const_2 **_sage_const_27  + _sage_const_1 )['x']; (x,) = R._first_ngens(1)
assert (x**_sage_const_4  - _sage_const_11 ).is_irreducible()
print("  BabyBear: x^4 - 11 is irreducible")

R2 = GF(_sage_const_2 **_sage_const_64  - _sage_const_2 **_sage_const_32  + _sage_const_1 )['x']; (x,) = R2._first_ngens(1)
assert (x**_sage_const_2  - _sage_const_7 ).is_irreducible()
print("  Goldilocks: x^2 - 7 is irreducible")

R3 = GF(_sage_const_2 **_sage_const_31  - _sage_const_1 )['x']; (x,) = R3._first_ngens(1)
assert (x**_sage_const_3  - _sage_const_5 ).is_irreducible()
print("  Mersenne-31: x^3 - 5 is irreducible")

