

# This file was *autogenerated* from the file sage/foundations/stark_fields.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)# SageMath: Cauchy MDS matrix
p = _sage_const_101   # small prime for demonstration
F = GF(p)
t = _sage_const_3 
xs = [F(i) for i in range(t)]
ys = [F(i + t) for i in range(t)]
M = matrix(F, t, t, lambda i, j: _sage_const_1  / (xs[i] - ys[j]))
print("Cauchy MDS matrix:")
print(M)
print(f"Determinant: {M.det()}")
# Verify all square submatrices are invertible
for size in range(_sage_const_1 , t + _sage_const_1 ):
    for rows in Combinations(range(t), size):
        for cols in Combinations(range(t), size):
            sub = M[rows, cols]
            assert sub.det() != _sage_const_0 , f"Singular submatrix at {rows}, {cols}"
print("All submatrices are invertible (MDS property verified)")

