

# This file was *autogenerated* from the file sage/cpu_efficiency/field_size_impact.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_31 = Integer(31); _sage_const_27 = Integer(27); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_32 = Integer(32); _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_254 = Integer(254); _sage_const_52435875175126190479447740508185965837690552500527637822603658699938581184513 = Integer(52435875175126190479447740508185965837690552500527637822603658699938581184513); _sage_const_255 = Integer(255); _sage_const_70 = Integer(70); _sage_const_63 = Integer(63)# SageMath: compare field sizes and their impact on arithmetic cost
# Larger fields need more limbs, making multiplication more expensive.

fields = [
    ("BabyBear", _sage_const_2 **_sage_const_31  - _sage_const_2 **_sage_const_27  + _sage_const_1 , _sage_const_31 ),
    ("Goldilocks", _sage_const_2 **_sage_const_64  - _sage_const_2 **_sage_const_32  + _sage_const_1 , _sage_const_64 ),
    ("BN254 scalar", _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 , _sage_const_254 ),
    ("BLS12-381 scalar", _sage_const_52435875175126190479447740508185965837690552500527637822603658699938581184513 , _sage_const_255 ),
]

print("Field size impact on CPU arithmetic cost")
print("=" * _sage_const_70 )
print(f"{'Field':>20} | {'Bits':>5} | {'_sage_const_64 -bit limbs':>12} | {'Mul cost (relative)':>20}")
print("-" * _sage_const_70 )
for name, p, bits in fields:
    limbs = (bits + _sage_const_63 ) // _sage_const_64 
    # Schoolbook multiplication: O(limbs^2)
    # Karatsuba: O(limbs^1.585)
    relative_cost = limbs**_sage_const_2 
    print(f"{name:>20} | {bits:>5} | {limbs:>12} | {relative_cost:>20}")

print()
print("Observations:")
print("- BabyBear fits in a single 32-bit word: mul is 1 CPU multiply")
print("- Goldilocks fits in a single 64-bit word with fast reduction")
print("- BN254/BLS fields need 4 limbs: mul costs ~16x more than BabyBear")
print("- STARKs over small fields (BabyBear, Goldilocks) are much faster")
print("  on CPU, which is why modern STARK provers prefer them")

