

# This file was *autogenerated* from the file sage/cpu_efficiency/inverse_sbox_cost.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_32 = Integer(32); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_123456789 = Integer(123456789)# SageMath: demonstrate the cost asymmetry of forward vs inverse S-box

p = _sage_const_2 **_sage_const_64  - _sage_const_2 **_sage_const_32  + _sage_const_1   # Goldilocks
F = GF(p)
alpha = _sage_const_7   # smallest alpha coprime to p-1 for Goldilocks (5 divides p-1)
alpha_inv = inverse_mod(alpha, p - _sage_const_1 )

print(f"Field: Goldilocks (p = 2^64 - 2^32 + 1)")
print(f"alpha = {alpha}")
print(f"alpha_inv = {alpha_inv}")
print(f"Bit length of alpha: {ZZ(alpha).nbits()}")
print(f"Bit length of alpha_inv: {ZZ(alpha_inv).nbits()}")
print()

# Count multiplications
fwd_bits = ZZ(alpha).digits(_sage_const_2 )
inv_bits = ZZ(alpha_inv).digits(_sage_const_2 )
fwd_muls = (len(fwd_bits) - _sage_const_1 ) + (sum(fwd_bits) - _sage_const_1 )
inv_muls = (len(inv_bits) - _sage_const_1 ) + (sum(inv_bits) - _sage_const_1 )

print(f"Forward x^{alpha}:")
print(f"  Binary: {ZZ(alpha).str(_sage_const_2 )}")
print(f"  Multiplications: {fwd_muls}")
print()
print(f"Inverse x^(1/{alpha}):")
print(f"  Binary length: {len(inv_bits)} bits")
print(f"  Hamming weight: {sum(inv_bits)}")
print(f"  Multiplications: {inv_muls}")
print()
print(f"Ratio: inverse is {int(inv_muls / fwd_muls)}x more expensive on CPU")
print()

# Verify correctness
x = F(_sage_const_123456789 )
y = x**alpha
z = y**alpha_inv
assert z == x
print(f"Verification: (x^{alpha})^(alpha_inv) == x? {z == x}")

