

# This file was *autogenerated* from the file sage/cpu_efficiency/sbox_mul_counts.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_64 = Integer(64); _sage_const_32 = Integer(32); _sage_const_65 = Integer(65); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11)# SageMath: measure relative cost of field operations
# We count the number of field multiplications as the cost metric,
# since multiplication dominates on CPU.

def count_muls_power(alpha):
    """
    Count field multiplications for x^alpha via square-and-multiply.
    """
    if alpha <= _sage_const_1 :
        return _sage_const_0 
    bits = ZZ(alpha).digits(_sage_const_2 )
    squarings = len(bits) - _sage_const_1 
    extra_muls = sum(bits) - _sage_const_1 
    return squarings + extra_muls

def count_muls_inverse_power(alpha, p):
    """
    Count field multiplications for x^(1/alpha) mod p.
    The inverse exponent is alpha_inv = inverse_mod(alpha, p-1),
    which is typically close to p in size.
    Returns None if alpha is not invertible mod p-1.
    """
    if gcd(alpha, p - _sage_const_1 ) != _sage_const_1 :
        return None
    alpha_inv = inverse_mod(alpha, p - _sage_const_1 )
    bits = ZZ(alpha_inv).digits(_sage_const_2 )
    squarings = len(bits) - _sage_const_1 
    extra_muls = sum(bits) - _sage_const_1 
    return squarings + extra_muls

# BN254 scalar field
p_bn254 = _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 
# Goldilocks
p_gold = _sage_const_2 **_sage_const_64  - _sage_const_2 **_sage_const_32  + _sage_const_1 

print("Field multiplication counts per S-box evaluation")
print("=" * _sage_const_65 )
print(f"{'alpha':>6} | {'x**alpha muls':>13} | {'x**(_sage_const_1 /alpha) BN254':>18} | {'x**(_sage_const_1 /alpha) Gold':>17}")
print("-" * _sage_const_65 )
for alpha in [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 ]:
    fwd = count_muls_power(alpha)
    inv_bn = count_muls_inverse_power(alpha, p_bn254)
    inv_gold = count_muls_inverse_power(alpha, p_gold)
    inv_bn_str = str(inv_bn) if inv_bn is not None else "N/A (not coprime)"
    inv_gold_str = str(inv_gold) if inv_gold is not None else "N/A (not coprime)"
    print(f"{alpha:>6} | {fwd:>13} | {inv_bn_str:>18} | {inv_gold_str:>17}")

print()
print("Key observation: the inverse S-box is ~100x more expensive on CPU")
print("than the forward S-box. This is the main CPU disadvantage of Rescue.")

