name: Test SageMath code

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: make lint-shell

  sage-tests:
    name: Run SageMath files
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
      options: --user root
    steps:
      - uses: actions/checkout@v6

      - name: Run all sage files
        run: .github/scripts/run-sage-tests.sh sage
